---
- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Enable nginx service
  service:
    name: nginx
    enabled: true

- name: Start nginx service
  service:
    name: nginx
    state: started

- name: Deploy WordPress vhost
  ansible.builtin.template:
    src: wordpress.conf.j2
    dest: /etc/nginx/sites-available/wordpress.conf
  notify: restart nginx

- name: Enable WordPress site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/wordpress.conf
    dest: /etc/nginx/sites-enabled/wordpress.conf
    state: link
  notify: restart nginx

- name: Remove default site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: Validate nginx configuration
  ansible.builtin.command: nginx -t
  changed_when: false
